### PR TITLE
Update Weather AI to the new API shape

### PR DESCRIPTION
**Pull request by tomayac**
Remove types (migrating to a published version of https://gist.github.com/swissspidy/477df0a812ba68fada7ab54695eb7a78 eventually)

### CODE REVIEW

**Review by andreban — APPROVED** [review]
LGTM

**Comment by tomayac** [comment]
Don't forget to redeploy on chrome.dev. Thanks!

**Comment by andreban** [comment]
Build is broken after this change. 

Screenshot 2024-09-04 at 11 56 21

**Comment by tomayac** [comment]
Opened https://github.com/GoogleChromeLabs/web-ai-demos/pull/35. If I may have an opinion, it's that we should not have a hard dependency on TypeScript for this demo repo. The focus should be on the code.

**Pull request merged**
